{
 "title": "Voltgate Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total HTTP Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_requests_total[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Blocked Requests Per Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_blocked_requests_total[$__rate_interval]))",
     "legendFormat": "{{target_service_name}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_requests_total[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Duration by Path (99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le, path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Response Size by Path (99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, path) (rate(http_response_size_bytes_bucket[$__rate_interval])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Voltgate Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"voltgate-server\"} |= ``"
    }
   ]
  }
 ]
}